apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yml
- backend/service.yml
- frontend/deployment.yml
- frontend/service.yml
- ingress.yml


images:
- name: 888500057930.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newName: 888500057930.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newTag: 06b2fa6ddf146bfb08aa59080906e598ed1ce07d
- name: 888500057930.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 888500057930.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: v1.0
